module.exports = [

    {
        city: "Santiago", 
        latitude: "-33.4500", 
        longitude: "-70.6667", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "primary", 
        population: "7007000", 
        population_proper: "236453"
      }, 
      {
        city: "Concepción", 
        latitude: "-36.8200", 
        longitude: "-73.0445", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "admin", 
        population: "889725", 
        population_proper: "212003"
      }, 
      {
        city: "Puente Alto", 
        latitude: "-33.6167", 
        longitude: "-70.5833", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "minor", 
        population: "573935", 
        population_proper: "573935"
      }, 
      {
        city: "Maipú", 
        latitude: "-33.5167", 
        longitude: "-70.7667", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "521627", 
        population_proper: "521627"
      }, 
      {
        city: "La Florida", 
        latitude: "-33.5500", 
        longitude: "-70.5667", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "366916", 
        population_proper: "366916"
      }, 
      {
        city: "Antofagasta", 
        latitude: "-23.6464", 
        longitude: "-70.3980", 
        country: "Chile", 
        iso2: "CL", 
        region: "Antofagasta", 
        capital: "admin", 
        population: "348517", 
        population_proper: "348517"
      }, 
      {
        city: "Viña del Mar", 
        latitude: "-33.0245", 
        longitude: "-71.5518", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "", 
        population: "332875", 
        population_proper: "332875"
      }, 
      {
        city: "San Bernardo", 
        latitude: "-33.6000", 
        longitude: "-70.7167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "minor", 
        population: "301313", 
        population_proper: "301313"
      }, 
      {
        city: "Valparaíso", 
        latitude: "-33.0458", 
        longitude: "-71.6197", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "admin", 
        population: "296655", 
        population_proper: "296655"
      }, 
      {
        city: "Temuco", 
        latitude: "-38.7399", 
        longitude: "-72.5901", 
        country: "Chile", 
        iso2: "CL", 
        region: "Araucanía", 
        capital: "admin", 
        population: "282415", 
        population_proper: "282415"
      }, 
      {
        city: "Las Condes", 
        latitude: "-33.4167", 
        longitude: "-70.5833", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "249893", 
        population_proper: "249893"
      }, 
      {
        city: "Rancagua", 
        latitude: "-34.1654", 
        longitude: "-70.7398", 
        country: "Chile", 
        iso2: "CL", 
        region: "Libertador General Bernardo O’Higgins", 
        capital: "admin", 
        population: "231370", 
        population_proper: "231370"
      }, 
      {
        city: "Talca", 
        latitude: "-35.4266", 
        longitude: "-71.6661", 
        country: "Chile", 
        iso2: "CL", 
        region: "Maule", 
        capital: "admin", 
        population: "206069", 
        population_proper: "206069"
      }, 
      {
        city: "Coquimbo", 
        latitude: "-29.9532", 
        longitude: "-71.3380", 
        country: "Chile", 
        iso2: "CL", 
        region: "Coquimbo", 
        capital: "minor", 
        population: "204068", 
        population_proper: "204068"
      }, 
      {
        city: "Arica", 
        latitude: "-18.4784", 
        longitude: "-70.3211", 
        country: "Chile", 
        iso2: "CL", 
        region: "Arica y Parinacota", 
        capital: "admin", 
        population: "202131", 
        population_proper: "202131"
      }, 
      {
        city: "La Serena", 
        latitude: "-29.9027", 
        longitude: "-71.2520", 
        country: "Chile", 
        iso2: "CL", 
        region: "Coquimbo", 
        capital: "admin", 
        population: "195382", 
        population_proper: "195382"
      }, 
      {
        city: "Iquique", 
        latitude: "-20.2141", 
        longitude: "-70.1524", 
        country: "Chile", 
        iso2: "CL", 
        region: "Tarapacá", 
        capital: "admin", 
        population: "188003", 
        population_proper: "188003"
      }, 
      {
        city: "Puerto Montt", 
        latitude: "-41.4718", 
        longitude: "-72.9396", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Lagos", 
        capital: "admin", 
        population: "169736", 
        population_proper: "169736"
      }, 
      {
        city: "Chillán", 
        latitude: "-36.6067", 
        longitude: "-72.1033", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "admin", 
        population: "164270", 
        population_proper: "164270"
      }, 
      {
        city: "Calama", 
        latitude: "-22.4624", 
        longitude: "-68.9272", 
        country: "Chile", 
        iso2: "CL", 
        region: "Antofagasta", 
        capital: "minor", 
        population: "157575", 
        population_proper: "157575"
      }, 
      {
        city: "Osorno", 
        latitude: "-40.5739", 
        longitude: "-73.1336", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Lagos", 
        capital: "minor", 
        population: "154131", 
        population_proper: "135773"
      }, 
      {
        city: "Copiapó", 
        latitude: "-27.3665", 
        longitude: "-70.3323", 
        country: "Chile", 
        iso2: "CL", 
        region: "Atacama", 
        capital: "admin", 
        population: "150804", 
        population_proper: "150804"
      }, 
      {
        city: "Valdivia", 
        latitude: "-39.8142", 
        longitude: "-73.2459", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Ríos", 
        capital: "admin", 
        population: "150048", 
        population_proper: "150048"
      }, 
      {
        city: "Quilpué", 
        latitude: "-33.0498", 
        longitude: "-71.4415", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "minor", 
        population: "147991", 
        population_proper: "147991"
      }, 
      {
        city: "Talcahuano", 
        latitude: "-36.7145", 
        longitude: "-73.1141", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "147831", 
        population_proper: "147831"
      }, 
      {
        city: "Colina", 
        latitude: "-33.2000", 
        longitude: "-70.6833", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "minor", 
        population: "146207", 
        population_proper: "146207"
      }, 
      {
        city: "Los Ángeles", 
        latitude: "-37.4707", 
        longitude: "-72.3517", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "minor", 
        population: "143023", 
        population_proper: "143023"
      }, 
      {
        city: "Villa Alemana", 
        latitude: "-33.0428", 
        longitude: "-71.3744", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "", 
        population: "125140", 
        population_proper: "125140"
      }, 
      {
        city: "Punta Arenas", 
        latitude: "-53.1627", 
        longitude: "-70.9081", 
        country: "Chile", 
        iso2: "CL", 
        region: "Magallanes y de la Antártica Chilena", 
        capital: "admin", 
        population: "123403", 
        population_proper: "123403"
      }, 
      {
        city: "La Granja", 
        latitude: "-33.5431", 
        longitude: "-70.6319", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "116571", 
        population_proper: "116571"
      }, 
      {
        city: "Coronel", 
        latitude: "-37.0167", 
        longitude: "-73.1333", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "116262", 
        population_proper: "116262"
      }, 
      {
        city: "Curicó", 
        latitude: "-34.9800", 
        longitude: "-71.2400", 
        country: "Chile", 
        iso2: "CL", 
        region: "Maule", 
        capital: "minor", 
        population: "113711", 
        population_proper: "102438"
      }, 
      {
        city: "Alto Hospicio", 
        latitude: "-20.2500", 
        longitude: "-70.1167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Tarapacá", 
        capital: "", 
        population: "108375", 
        population_proper: "108375"
      }, 
      {
        city: "Lo Barnechea", 
        latitude: "-33.3500", 
        longitude: "-70.5167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "105833", 
        population_proper: "105833"
      }, 
      {
        city: "Espejo", 
        latitude: "-33.5333", 
        longitude: "-70.7167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "98804", 
        population_proper: "98804"
      }, 
      {
        city: "Buin", 
        latitude: "-33.7333", 
        longitude: "-70.7500", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "96614", 
        population_proper: "96614"
      }, 
      {
        city: "San Joaquín", 
        latitude: "-33.5000", 
        longitude: "-70.6167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "94492", 
        population_proper: "94492"
      }, 
      {
        city: "La Reina", 
        latitude: "-33.4500", 
        longitude: "-70.5500", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "92787", 
        population_proper: "92787"
      }, 
      {
        city: "Peñaflor", 
        latitude: "-33.6167", 
        longitude: "-70.9167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "90201", 
        population_proper: "90201"
      }, 
      {
        city: "San Antonio", 
        latitude: "-33.5809", 
        longitude: "-71.6132", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "minor", 
        population: "86239", 
        population_proper: "86239"
      }, 
      {
        city: "Chiguayante", 
        latitude: "-36.9167", 
        longitude: "-73.0167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "85863", 
        population_proper: "85863"
      }, 
      {
        city: "Ovalle", 
        latitude: "-30.6031", 
        longitude: "-71.2030", 
        country: "Chile", 
        iso2: "CL", 
        region: "Coquimbo", 
        capital: "minor", 
        population: "75864", 
        population_proper: "75864"
      }, 
      {
        city: "Linares", 
        latitude: "-35.8454", 
        longitude: "-71.5979", 
        country: "Chile", 
        iso2: "CL", 
        region: "Maule", 
        capital: "minor", 
        population: "73602", 
        population_proper: "73602"
      }, 
      {
        city: "Quillota", 
        latitude: "-32.8799", 
        longitude: "-71.2474", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "minor", 
        population: "73261", 
        population_proper: "73261"
      }, 
      {
        city: "San Felipe", 
        latitude: "-32.7507", 
        longitude: "-70.7251", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "minor", 
        population: "64120", 
        population_proper: "64120"
      }, 
      {
        city: "Coyhaique", 
        latitude: "-45.5712", 
        longitude: "-72.0685", 
        country: "Chile", 
        iso2: "CL", 
        region: "Aysén", 
        capital: "admin", 
        population: "61210", 
        population_proper: "61210"
      }, 
      {
        city: "Los Andes", 
        latitude: "-32.8337", 
        longitude: "-70.5982", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "minor", 
        population: "59388", 
        population_proper: "59388"
      }, 
      {
        city: "San Fernando", 
        latitude: "-34.5839", 
        longitude: "-70.9891", 
        country: "Chile", 
        iso2: "CL", 
        region: "Libertador General Bernardo O’Higgins", 
        capital: "minor", 
        population: "58367", 
        population_proper: "58367"
      }, 
      {
        city: "Talagante", 
        latitude: "-33.6667", 
        longitude: "-70.9333", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "minor", 
        population: "56990", 
        population_proper: "56990"
      }, 
      {
        city: "Villarrica", 
        latitude: "-39.2667", 
        longitude: "-72.2167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Araucanía", 
        capital: "", 
        population: "55478", 
        population_proper: "55478"
      }, 
      {
        city: "La Calera", 
        latitude: "-32.7833", 
        longitude: "-71.2167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "", 
        population: "50554", 
        population_proper: "50554"
      }, 
      {
        city: "Angol", 
        latitude: "-37.7988", 
        longitude: "-72.7086", 
        country: "Chile", 
        iso2: "CL", 
        region: "Araucanía", 
        capital: "minor", 
        population: "48608", 
        population_proper: "48608"
      }, 
      {
        city: "Penco", 
        latitude: "-36.7333", 
        longitude: "-72.9833", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "47367", 
        population_proper: "47367"
      }, 
      {
        city: "Vallenar", 
        latitude: "-28.5700", 
        longitude: "-70.7600", 
        country: "Chile", 
        iso2: "CL", 
        region: "Atacama", 
        capital: "minor", 
        population: "44895", 
        population_proper: "30858"
      }, 
      {
        city: "Lota", 
        latitude: "-37.0944", 
        longitude: "-73.1563", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "43272", 
        population_proper: "43272"
      }, 
      {
        city: "Tomé", 
        latitude: "-36.6171", 
        longitude: "-72.9575", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "42312", 
        population_proper: "42312"
      }, 
      {
        city: "Alerce", 
        latitude: "-41.3969", 
        longitude: "-72.9037", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Lagos", 
        capital: "", 
        population: "42267", 
        population_proper: "42267"
      }, 
      {
        city: "Parral", 
        latitude: "-36.1500", 
        longitude: "-71.8333", 
        country: "Chile", 
        iso2: "CL", 
        region: "Maule", 
        capital: "", 
        population: "39404", 
        population_proper: "39404"
      }, 
      {
        city: "Placilla de Peñuelas", 
        latitude: "-33.1156", 
        longitude: "-71.5678", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "", 
        population: "39344", 
        population_proper: "39344"
      }, 
      {
        city: "Ancud", 
        latitude: "-41.8682", 
        longitude: "-73.8287", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Lagos", 
        capital: "", 
        population: "38991", 
        population_proper: "38991"
      }, 
      {
        city: "Constitución", 
        latitude: "-35.3333", 
        longitude: "-72.4167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Maule", 
        capital: "", 
        population: "37917", 
        population_proper: "15888"
      }, 
      {
        city: "Lampa", 
        latitude: "-33.2864", 
        longitude: "-70.8729", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "37599", 
        population_proper: "37599"
      }, 
      {
        city: "Isla de Maipo", 
        latitude: "-33.7500", 
        longitude: "-70.9000", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "", 
        population: "36219", 
        population_proper: "36219"
      }, 
      {
        city: "Victoria", 
        latitude: "-38.2167", 
        longitude: "-72.3333", 
        country: "Chile", 
        iso2: "CL", 
        region: "Araucanía", 
        capital: "", 
        population: "34890", 
        population_proper: "34890"
      }, 
      {
        city: "Cañete", 
        latitude: "-37.8000", 
        longitude: "-73.3833", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "34537", 
        population_proper: "34537"
      }, 
      {
        city: "Castro", 
        latitude: "-42.4824", 
        longitude: "-73.7643", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Lagos", 
        capital: "minor", 
        population: "33417", 
        population_proper: "33417"
      }, 
      {
        city: "Curanilahue", 
        latitude: "-37.4667", 
        longitude: "-73.3500", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "32288", 
        population_proper: "32288"
      }, 
      {
        city: "Concón", 
        latitude: "-32.9167", 
        longitude: "-71.5167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "", 
        population: "32273", 
        population_proper: "32273"
      }, 
      {
        city: "Quintero", 
        latitude: "-32.7833", 
        longitude: "-71.5333", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "", 
        population: "31923", 
        population_proper: "31923"
      }, 
      {
        city: "Nueva Imperial", 
        latitude: "-38.7333", 
        longitude: "-72.9500", 
        country: "Chile", 
        iso2: "CL", 
        region: "Araucanía", 
        capital: "", 
        population: "31632", 
        population_proper: "31632"
      }, 
      {
        city: "Cauquenes", 
        latitude: "-35.9671", 
        longitude: "-72.3154", 
        country: "Chile", 
        iso2: "CL", 
        region: "Maule", 
        capital: "minor", 
        population: "31362", 
        population_proper: "16948"
      }, 
      {
        city: "San Javier", 
        latitude: "-35.5924", 
        longitude: "-71.7353", 
        country: "Chile", 
        iso2: "CL", 
        region: "Maule", 
        capital: "", 
        population: "29017", 
        population_proper: "29017"
      }, 
      {
        city: "Pucón", 
        latitude: "-39.2667", 
        longitude: "-71.9667", 
        country: "Chile", 
        iso2: "CL", 
        region: "Araucanía", 
        capital: "", 
        population: "28923", 
        population_proper: "28923"
      }, 
      {
        city: "Chillán Viejo", 
        latitude: "-36.6229", 
        longitude: "-72.1317", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "27359", 
        population_proper: "27359"
      }, 
      {
        city: "La Unión", 
        latitude: "-40.2952", 
        longitude: "-73.0822", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Ríos", 
        capital: "minor", 
        population: "26517", 
        population_proper: "26517"
      }, 
      {
        city: "Puerto Varas", 
        latitude: "-41.3178", 
        longitude: "-72.9827", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Lagos", 
        capital: "", 
        population: "26172", 
        population_proper: "26172"
      }, 
      {
        city: "Carahue", 
        latitude: "-38.7000", 
        longitude: "-73.1667", 
        country: "Chile", 
        iso2: "CL", 
        region: "Araucanía", 
        capital: "", 
        population: "25696", 
        population_proper: "25696"
      }, 
      {
        city: "Salamanca", 
        latitude: "-31.7667", 
        longitude: "-70.9667", 
        country: "Chile", 
        iso2: "CL", 
        region: "Coquimbo", 
        capital: "", 
        population: "25326", 
        population_proper: "25326"
      }, 
      {
        city: "Las Cabras", 
        latitude: "-34.3000", 
        longitude: "-71.3167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Libertador General Bernardo O’Higgins", 
        capital: "", 
        population: "24640", 
        population_proper: "24640"
      }, 
      {
        city: "Tocopilla", 
        latitude: "-22.0941", 
        longitude: "-70.2010", 
        country: "Chile", 
        iso2: "CL", 
        region: "Antofagasta", 
        capital: "minor", 
        population: "24460", 
        population_proper: "20251"
      }, 
      {
        city: "Cartagena", 
        latitude: "-33.5500", 
        longitude: "-71.6000", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "", 
        population: "22738", 
        population_proper: "22738"
      }, 
      {
        city: "Lebu", 
        latitude: "-37.6103", 
        longitude: "-73.6561", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "minor", 
        population: "22345", 
        population_proper: "10904"
      }, 
      {
        city: "La Cruz", 
        latitude: "-32.8167", 
        longitude: "-71.2333", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "", 
        population: "22098", 
        population_proper: "22098"
      }, 
      {
        city: "Casablanca", 
        latitude: "-33.3167", 
        longitude: "-71.4167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "", 
        population: "21874", 
        population_proper: "21874"
      }, 
      {
        city: "Los Vilos", 
        latitude: "-31.9000", 
        longitude: "-71.5167", 
        country: "Chile", 
        iso2: "CL", 
        region: "Coquimbo", 
        capital: "", 
        population: "21382", 
        population_proper: "21382"
      }, 
      {
        city: "Hualqui", 
        latitude: "-36.9759", 
        longitude: "-72.9384", 
        country: "Chile", 
        iso2: "CL", 
        region: "Biobío", 
        capital: "", 
        population: "20968", 
        population_proper: "20968"
      }, 
      {
        city: "Purranque", 
        latitude: "-40.9167", 
        longitude: "-73.1667", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Lagos", 
        capital: "", 
        population: "20949", 
        population_proper: "20949"
      }, 
      {
        city: "Illapel", 
        latitude: "-31.6327", 
        longitude: "-71.1683", 
        country: "Chile", 
        iso2: "CL", 
        region: "Coquimbo", 
        capital: "minor", 
        population: "20751", 
        population_proper: "20751"
      }, 
      {
        city: "Pichidegua", 
        latitude: "-34.3500", 
        longitude: "-71.3000", 
        country: "Chile", 
        iso2: "CL", 
        region: "Libertador General Bernardo O’Higgins", 
        capital: "", 
        population: "19714", 
        population_proper: "19714"
      }, 
      {
        city: "La Ligua", 
        latitude: "-32.4494", 
        longitude: "-71.2317", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "minor", 
        population: "19127", 
        population_proper: "19127"
      }, 
      {
        city: "Puerto Natales", 
        latitude: "-51.7263", 
        longitude: "-72.5062", 
        country: "Chile", 
        iso2: "CL", 
        region: "Magallanes y de la Antártica Chilena", 
        capital: "minor", 
        population: "19023", 
        population_proper: "19023"
      }, 
      {
        city: "Puerto Aysén", 
        latitude: "-45.4068", 
        longitude: "-72.6977", 
        country: "Chile", 
        iso2: "CL", 
        region: "Aysén", 
        capital: "minor", 
        population: "17441", 
        population_proper: "17441"
      }, 
      {
        city: "Pichilemu", 
        latitude: "-34.3851", 
        longitude: "-72.0049", 
        country: "Chile", 
        iso2: "CL", 
        region: "Libertador General Bernardo O’Higgins", 
        capital: "minor", 
        population: "12776", 
        population_proper: "12776"
      }, 
      {
        city: "Pozo Almonte", 
        latitude: "-20.2597", 
        longitude: "-69.7862", 
        country: "Chile", 
        iso2: "CL", 
        region: "Tarapacá", 
        capital: "minor", 
        population: "9277", 
        population_proper: "9277"
      }, 
      {
        city: "Hanga Roa", 
        latitude: "-27.1492", 
        longitude: "-109.4323", 
        country: "Chile", 
        iso2: "CL", 
        region: "Valparaíso", 
        capital: "minor", 
        population: "7163", 
        population_proper: "7163"
      }, 
      {
        city: "Porvenir", 
        latitude: "-53.2956", 
        longitude: "-70.3687", 
        country: "Chile", 
        iso2: "CL", 
        region: "Magallanes y de la Antártica Chilena", 
        capital: "minor", 
        population: "5992", 
        population_proper: "5992"
      }, 
      {
        city: "Chaitén", 
        latitude: "-42.9193", 
        longitude: "-72.7088", 
        country: "Chile", 
        iso2: "CL", 
        region: "Los Lagos", 
        capital: "minor", 
        population: "5071", 
        population_proper: "5071"
      }, 
      {
        city: "Chile Chico", 
        latitude: "-46.5376", 
        longitude: "-71.7293", 
        country: "Chile", 
        iso2: "CL", 
        region: "Aysén", 
        capital: "minor", 
        population: "3129", 
        population_proper: "3129"
      }, 
      {
        city: "Cochrane", 
        latitude: "-47.2539", 
        longitude: "-72.5732", 
        country: "Chile", 
        iso2: "CL", 
        region: "Aysén", 
        capital: "minor", 
        population: "2789", 
        population_proper: "2789"
      }, 
      {
        city: "Puerto Williams", 
        latitude: "-54.9341", 
        longitude: "-67.6109", 
        country: "Chile", 
        iso2: "CL", 
        region: "Magallanes y de la Antártica Chilena", 
        capital: "minor", 
        population: "1868", 
        population_proper: "1868"
      }, 
      {
        city: "Melipilla", 
        latitude: "-33.6855", 
        longitude: "-71.2146", 
        country: "Chile", 
        iso2: "CL", 
        region: "Región Metropolitana", 
        capital: "minor", 
        population: "", 
        population_proper: ""
      }, 
      {
        city: "Chañaral", 
        latitude: "-26.3479", 
        longitude: "-70.6224", 
        country: "Chile", 
        iso2: "CL", 
        region: "Atacama", 
        capital: "minor", 
        population: "", 
        population_proper: ""
      }, 
      {
        city: "Putre", 
        latitude: "-18.1964", 
        longitude: "-69.5592", 
        country: "Chile", 
        iso2: "CL", 
        region: "Arica y Parinacota", 
        capital: "minor", 
        population: "", 
        population_proper: ""
      }
    ]